---
# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Check if the input variables exist
  ansible.builtin.stat:
    path: '{{ cifmw_ceph_client_vars }}'
  register: ceph_input_vars
  when: cifmw_ceph_client_vars is defined

- name: Load variables produced by the cephadm provisioning process
  ansible.builtin.include_vars: '{{ cifmw_ceph_client_vars }}'
  when:
    - cifmw_ceph_client_vars is defined
    - ceph_input_vars.stat.exists | bool

- name: Render keys provided for the Ceph cluster
  ansible.builtin.include_tasks: create_keys.yml
  when:
    - (cifmw_ceph_client_keys is defined) or (keys is defined)
  vars:
    ceph_keys: |
      {% if cifmw_ceph_client_keys | length > 0 %}
      {% set client_keys = cifmw_ceph_client_keys %}
      {% elif keys is defined and keys is mapping %}
      {% set client_keys = keys.get('keys', {}) %}
      {% else %}
      {% set client_keys = keys %}
      {% endif %}
      {{ client_keys }}

- name: Render ceph config for the Ceph Clients
  ansible.builtin.include_tasks: create_ceph_conf.yml
  vars:
    config_overrides: |
      {% if cifmw_ceph_client_config_overrides is defined and cifmw_ceph_client_config_overrides | length > 0 %}
      {% set overrides = cifmw_ceph_client_config_overrides %}
      {% elif ceph_overrides is defined %}
      {% set overrides = ceph_overrides.get('ceph_conf_overrides', {}) %}
      {% else %}
      {% set overrides = {} %}
      {% endif %}
      {{ overrides }}

- name: Base64 encode ceph.conf file
  tags: k8s
  ansible.builtin.slurp:
    src: "{{ cifmw_ceph_client_fetch_dir }}/{{ cifmw_ceph_client_cluster | default('ceph') }}.conf"
  register: cifmw_ceph_client_conf_file_b64
  delegate_to: localhost
  no_log: true

- name: Base64 encode cephx key file
  tags: k8s
  ansible.builtin.slurp:
    src: "{{ cifmw_ceph_client_fetch_dir }}/{{ cifmw_ceph_client_cluster | default('ceph') }}.client.openstack.keyring"
  register: cifmw_ceph_client_key_file_b64
  delegate_to: localhost
  no_log: true

- name: Create k8s_ceph_secret.yml with base64 encoded files
  tags: k8s
  ansible.builtin.template:
    src: templates/k8s_ceph_secret.yml.j2
    dest: "{{ cifmw_ceph_client_fetch_dir }}/k8s_ceph_secret.yml"
    mode: "0600"
    force: true

- name: Get ceph RGW endpoint API endpoint
  ansible.builtin.shell:
    cmd: |
      set -xe -o pipefail
      oc rsh -n {{ namespace }} openstackclient openstack endpoint list --interface internal --service swift -c URL -f value | cut -d "/" -f 1,2,3
  register: reg_ceph_rgw_s3_endpoint
  changed_when: "'stdout' in reg_ceph_rgw_s3_endpoint"
  failed_when: (reg_ceph_rgw_s3_endpoint.rc | int) >= 1

- name: Discover ceph RGW settings
  ansible.builtin.set_fact:
    ceph_s3_access_key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters','digits'], length=32) }}"
    ceph_s3_secret_key: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters','digits'], length=32) }}"
    ceph_s3_bucket: "{{ cifmw_ceph_client_rgw_bucket_name }}"
    ceph_s3_endpoint: "{{ reg_ceph_rgw_s3_endpoint.stdout }}"

- name: Create glance secrets for ceph S3 backend
  ansible.builtin.template:
    src: templates/k8s_ceph_rgw_glance_secret.j2
    dest: "{{ cifmw_ceph_client_fetch_dir }}/k8s_ceph_rgw_glance_secret.yaml"
    mode: "0640"
    force: true

- name: Create ec2 credentials
  ansible.builtin.shell: |-
    set -xe -o pipefail
    oc rsh -n {{ namespace }} openstackclient openstack credential create --type ec2 --project admin admin '{"access": "{{ ceph_s3_access_key }}", "secret": "{{ ceph_s3_secret_key }}"}'
  changed_when: false

- name: Apply S3 backend secrets
  ansible.builtin.shell:
    cmd: |
      set -xe -o pipefail
      oc -n {{ namespace }} apply -f {{ cifmw_ceph_client_fetch_dir }}/k8s_ceph_rgw_glance_secret.yaml
  register: s3_secrets_oc_apply_result
  changed_when: ('stdout' in s3_secrets_oc_apply_result) and ('unchanged' not in s3_secrets_oc_apply_result.stdout)
  failed_when: ( s3_secrets_oc_apply_result.rc | int ) >= 1

- name: Create edpm-values-post-ceph ConfigMap if sample path provided
  ansible.builtin.include_tasks: edpm_values_post_ceph.yml
  when:
    - cifmw_ceph_client_values_post_ceph_path_src is defined
    - cifmw_ceph_client_values_post_ceph_path_src | length > 0

- name: Create edpm-service-values-post-ceph ConfigMap if sample path provided
  ansible.builtin.include_tasks: edpm_service_values_post_ceph.yml
  when:
    - cifmw_ceph_client_service_values_post_ceph_path_src is defined
    - cifmw_ceph_client_service_values_post_ceph_path_src | length > 0
